# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20160102_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='courseName',
        ),
    ]
