# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20160102_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='qp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
