# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20160112_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='sid',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
